u-name: ceshi
dubbo:
  application:
    name: consumer-aaa

  protocol:
    name: dubbo
    port: -1
  registries:
#    registry-query-service:
#      address: zookeeper://zk.dev.xinshiyun.com:12181?timeout=120000
#      group: query-service-group
#    registry-domain-service:
#      address: zookeeper://127.0.0.1:2181
#      group: domain-service-group
    registry-ddr:
      address: zookeeper://zk.dev.xinshiyun.com:12181?timeout=120000
      group: ddr-domain-ddr
      check: false
  consumer:
    query-service: query-service-provider-group
    domain-service: domain-service-provider-group
    check: false
#    router: local_tag


#  registry:
#    id: zk-registry
#    address: zookeeper://127.0.0.1:2181
#  config-center:
#    address: zookeeper://127.0.0.1:2181
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
