dubbo:
  application:
    name: query-service
  protocol:
    name: dubbo
    port: -1
  registries:
    registry-query-service:
      address: zookeeper://zk.dev.xinshiyun.com:12181?timeout=120000
      group: query-service-group
  provider:
    group: query-service-provider-group



